"""
Django settings for siscr project.

Generated by 'django-admin startproject' using Django X.Y.Z.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Defina sua chave secreta aqui, ou carregue de variáveis de ambiente
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-sua-chave-secreta-aqui') 

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG será configurado baseado no ENVIRONMENT abaixo
DEBUG = True  # Valor padrão, será sobrescrito se ENVIRONMENT estiver definido

# CORREÇÃO: Necessário para rodar o servidor quando DEBUG=False. 
# Mesmo com DEBUG=True, é bom configurar para localhost.
# ALLOWED_HOSTS será configurado baseado no ENVIRONMENT abaixo
ALLOWED_HOSTS = [
    '127.0.0.1', 
    'localhost',
    'teste-tenant.localhost',  # Domínio do tenant de teste
    'comercio_simples.localhost',  # Domínio do tenant Comércio Simples
]  # Valor padrão, será sobrescrito se ENVIRONMENT estiver definido



# Application definition

# IMPORTANTE: Para django-tenants, apps são divididos em SHARED_APPS e TENANT_APPS
SHARED_APPS = [
    # Django tenants deve vir primeiro
    'django_tenants',
    
    # Django padrão (shared):
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.admin',
    'django.contrib.staticfiles',
    
    # Third-party apps (shared):
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'guardian',
    'django_extensions',
    'django_ratelimit',
    
    # Tenant app (shared):
    'tenants',  # App de tenants (deve estar em SHARED)
    
    # SaaS apps (shared):
    'subscriptions.apps.SubscriptionsConfig',  # App de assinaturas (deve estar em SHARED)
    'public',  # App para páginas públicas (signup, etc.)
    'payments',  # App de pagamentos (Stripe)
    'accounts',  # App de autenticação e permissões (UserProfile e TenantMembership precisam estar no schema público)
]

TENANT_APPS = [
    # Apps que pertencem aos tenants (cada tenant tem seu próprio schema)
    'django.contrib.contenttypes',
    'core',  # App core (views gerais, dashboard, etc.)
    'cadastros',  # App de cadastros (Pessoa, Produto, Servico)
]

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

MIDDLEWARE = [
    # CORS deve vir PRIMEIRO para processar requisições OPTIONS (preflight)
    'corsheaders.middleware.CorsMiddleware',
    # Middleware customizado para identificar tenant por header (deve vir ANTES do TenantMainMiddleware)
    'siscr.middleware.TenantDomainHeaderMiddleware',
    # Tenant middleware customizado que não retorna 404 quando tenant já está configurado
    'siscr.middleware.CustomTenantMainMiddleware',
    # Middleware para preservar URLs do tenant após TenantMainMiddleware
    'siscr.middleware.PreserveTenantURLsMiddleware',
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'siscr.middleware.DisableCSRFForAPI',  # Desabilita CSRF para APIs (deve vir antes do CSRF middleware)
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.AuditMiddleware',  # Middleware de auditoria (preenche created_by, updated_by, owner)
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # Middleware de quotas (verifica assinatura e limites)
    'subscriptions.middleware.QuotaMiddleware',
]

# ROOT_URLCONF não é usado pelo django-tenants
# O django-tenants usa PUBLIC_SCHEMA_URLCONF e TENANT_SCHEMA_URLCONF
# Mas precisamos definir para compatibilidade
ROOT_URLCONF = 'siscr.public_urls'  # Usar public_urls como padrão

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Busca templates na pasta 'templates' na raiz do projeto
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'siscr.wsgi.application'


# Database
# Configuração do PostgreSQL com django-tenants
DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': os.environ.get('DB_NAME', 'siscr_db'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# Database Router para django-tenants
DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

# Configuração de Tenants
TENANT_MODEL = "tenants.Tenant"  # Model que representa o tenant
TENANT_DOMAIN_MODEL = "tenants.Domain"  # Model que representa o domínio

# Public schema (schema compartilhado)
DEFAULT_SCHEMA_NAME = 'public'

# Para desenvolvimento: usar domínio padrão quando não houver subdomínio
SHOW_PUBLIC_IF_NO_TENANT_FOUND = True

# Configuração de URLs por schema
# URLs para schema público (quando não há tenant identificado)
PUBLIC_SCHEMA_URLCONF = 'siscr.public_urls'

# URLs para schemas de tenants (quando tenant é identificado)
TENANT_SCHEMA_URLCONF = 'siscr.tenant_urls'

# ============================================
# ENVIRONMENT CONFIGURATION (deve vir antes de outras configurações que dependem dele)
# ============================================
# Ambientes: development, homologation, preprod, production
ENVIRONMENT = os.environ.get('ENVIRONMENT', 'development')

# ============================================
# CACHE CONFIGURATION
# ============================================
# Cache para rate limiting e outras funcionalidades
# django-ratelimit requer cache com suporte a atomic increment
# Em desenvolvimento: Redis (mesmo que em produção para compatibilidade)
# Em produção: Redis
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1')

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': REDIS_URL,
    }
}

# ============================================
# RATE LIMITING SETTINGS
# ============================================
# Configuração de rate limiting para segurança
# Usa cache do Django (Redis recomendado em produção)
RATELIMIT_USE_CACHE = 'default'  # Usa o cache padrão do Django

# Configurações de rate limit por endpoint
RATELIMIT_ENABLE = True  # Habilitar rate limiting
RATELIMIT_SWITCH_OFF = False  # Desabilitar apenas para testes

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
# Onde o Django vai procurar arquivos estáticos globais. 
# Você deve criar essa pasta na raiz do projeto (C:\siscr\static)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model (comentado temporariamente para migrations)
# AUTH_USER_MODEL = 'accounts.User'

# CONFIGURAÇÃO DE LOGIN
# Nota: O login foi migrado para React (porta 5173)
# Estas configurações são mantidas apenas para compatibilidade com Django Admin
# Redireciona o usuário para o dashboard após o login bem-sucedido
LOGIN_REDIRECT_URL = '/admin/'  # Redireciona para admin já que não há mais templates de login
# LOGIN_URL removido - login agora está no React (http://localhost:5173/login)

# ============================================
# DJANGO REST FRAMEWORK
# ============================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # Para admin Django
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

# ============================================
# JWT SETTINGS
# ============================================
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ============================================
# CORS SETTINGS
# ============================================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React default
    "http://localhost:5173",  # Vite default
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
    # Domínios de tenant para desenvolvimento
    "http://teste-tenant.localhost:5173",
    "http://teste-tenant.localhost:3000",
]

# Em desenvolvimento, permitir todas as origens para facilitar testes
# IMPORTANTE: CORS_ALLOW_ALL_ORIGINS deve ser True em desenvolvimento
# para permitir requisições do frontend (localhost:5173)
CORS_ALLOW_ALL_ORIGINS = True if ENVIRONMENT == 'development' else False

# Permitir subdomínios de localhost em desenvolvimento
CORS_ALLOWED_ORIGIN_REGEXES = []
if ENVIRONMENT == 'development':
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^http://.*\.localhost:\d+$",  # Qualquer subdomínio de localhost com qualquer porta
        r"^http://localhost:\d+$",  # localhost com qualquer porta
        r"^http://127\.0\.0\.1:\d+$",  # 127.0.0.1 com qualquer porta
    ]

CORS_ALLOW_CREDENTIALS = True

# Headers permitidos em requisições CORS
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-tenant-domain',  # Header customizado para identificar tenant
]

# CORS_ALLOW_ALL_ORIGINS agora é definido acima baseado no ENVIRONMENT

# ============================================
# CSRF SETTINGS (para desenvolvimento)
# ============================================
# Configurações de CSRF para funcionar com django-tenants
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://127.0.0.1:5173',
    'http://localhost:5173',
    # Domínios de tenant para desenvolvimento
    'http://teste-tenant.localhost:8000',
    'http://teste-tenant.localhost:5173',
]

# Permitir cookies em requisições cross-origin
CSRF_COOKIE_SECURE = False  # True em produção com HTTPS
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'

# Sessões
SESSION_COOKIE_SECURE = False  # True em produção com HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# ============================================
# GUARDIAN SETTINGS
# ============================================
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # Default Django
    'guardian.backends.ObjectPermissionBackend',  # Guardian
)

# ============================================
# ============================================
# EMAIL SETTINGS
# ============================================
# Configuração de email para recuperação de senha e notificações
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND', 
    'django.core.mail.backends.console.EmailBackend'  # Console para desenvolvimento
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'SISCR <noreply@siscr.com.br>')

# URL do frontend para links de email
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# Debug baseado no ambiente (sobrescreve valor padrão acima)
# ENVIRONMENT já está definido acima (linha 150)
if ENVIRONMENT == 'production':
    DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'
else:
    DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

# Allowed hosts baseado no ambiente (sobrescreve valor padrão acima)
# ENVIRONMENT já está definido acima (linha 167)
if ENVIRONMENT == 'production':
    ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else []
elif ENVIRONMENT == 'preprod':
    ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'preprod.siscr.com.br').split(',')
elif ENVIRONMENT == 'homologation':
    ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'homolog.siscr.com.br').split(',')
else:  # development
    # Em desenvolvimento, manter hosts padrão
    # O middleware não modifica mais o HTTP_HOST quando tenant já está configurado via header
    # Isso resolve o problema de ALLOWED_HOSTS
    # Se necessário adicionar mais hosts, adicione aqui
    pass  # Mantém valores padrão definidos acima

# ============================================
# STRIPE CONFIGURATION
# ============================================
# Modo do Stripe: simulated (dev), test (homolog/preprod), live (production)
# Em development, usar 'test' para usar Stripe real (sandbox) ou 'simulated' para simular
STRIPE_MODE = os.environ.get('STRIPE_MODE', 'test' if ENVIRONMENT == 'development' else 'test')

# Chaves do Stripe por ambiente
if ENVIRONMENT == 'production':
    STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
    STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
    STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
elif ENVIRONMENT in ['preprod', 'homologation']:
    STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY_TEST', '')
    STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY_TEST', '')
    STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET_TEST', '')
else:  # development
    # Chaves de teste do Stripe (sandbox)
    # Configure via variáveis de ambiente: STRIPE_SECRET_KEY_TEST e STRIPE_PUBLISHABLE_KEY_TEST
    STRIPE_SECRET_KEY_TEST = os.environ.get('STRIPE_SECRET_KEY_TEST', '')
    STRIPE_PUBLISHABLE_KEY_TEST = os.environ.get('STRIPE_PUBLISHABLE_KEY_TEST', '')
    STRIPE_WEBHOOK_SECRET_TEST = os.environ.get('STRIPE_WEBHOOK_SECRET_TEST', '')
    # Mantém compatibilidade com código que usa STRIPE_SECRET_KEY
    STRIPE_SECRET_KEY = STRIPE_SECRET_KEY_TEST
    STRIPE_PUBLISHABLE_KEY = STRIPE_PUBLISHABLE_KEY_TEST
    STRIPE_WEBHOOK_SECRET = STRIPE_WEBHOOK_SECRET_TEST

# URLs do Stripe
STRIPE_API_VERSION = '2024-11-20.acacia'

# ============================================
# SENTRY (será configurado depois)
# ============================================
# import sentry_sdk
# from sentry_sdk.integrations.django import DjangoIntegration
# 
# sentry_sdk.init(
#     dsn=os.environ.get('SENTRY_DSN'),
#     integrations=[DjangoIntegration()],
#     traces_sample_rate=1.0,
#     send_default_pii=True,
# )