# Generated by Django 4.2.26 on 2025-12-31 18:03

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0002_increase_cpf_cnpj_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0004_tenant_last_backup_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro', verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica se o registro foi excluído (soft delete)', verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi excluído', null=True, verbose_name='Data de Exclusão')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Location')),
                ('codigo', models.CharField(help_text='Código único para identificar a location', max_length=50, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('LOJA', 'Loja'), ('ALMOXARIFADO', 'Almoxarifado'), ('ARMAZEM', 'Armazém'), ('CENTRO_DISTRIBUICAO', 'Centro de Distribuição'), ('ESTOQUE_TERCEIRO', 'Estoque em Terceiros'), ('OUTRO', 'Outro')], max_length=30, verbose_name='Tipo de Location')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('letra', models.CharField(blank=True, max_length=2, null=True, verbose_name='Letra')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Coordenada para cálculo de distância/proximidade', max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Coordenada para cálculo de distância/proximidade', max_digits=11, null=True, verbose_name='Longitude')),
                ('responsavel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('permite_entrada', models.BooleanField(default=True, help_text='Se esta location pode receber entradas de estoque', verbose_name='Permite Entrada')),
                ('permite_saida', models.BooleanField(default=True, help_text='Se esta location pode fazer saídas de estoque', verbose_name='Permite Saída')),
                ('permite_transferencia', models.BooleanField(default=True, help_text='Se esta location pode receber/enviar transferências', verbose_name='Permite Transferência')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Usuário que excluiu o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('empresa', models.ForeignKey(help_text='Empresa proprietária da location (obrigatório)', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tenants.empresa', verbose_name='Empresa')),
                ('filial', models.ForeignKey(blank=True, help_text='Filial específica (opcional). Se vazio, location é da empresa.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tenants.filial', verbose_name='Filial')),
                ('owner', models.ForeignKey(blank=True, help_text='Proprietário do registro (pode ser diferente de quem criou)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que fez a última modificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['empresa', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro', verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica se o registro foi excluído (soft delete)', verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi excluído', null=True, verbose_name='Data de Exclusão')),
                ('quantidade_atual', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantidade Atual')),
                ('quantidade_reservada', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantidade Reservada')),
                ('quantidade_disponivel', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=10, verbose_name='Quantidade Disponível')),
                ('quantidade_prevista_entrada', models.DecimalField(decimal_places=3, default=0, help_text='Quantidade esperada em entradas futuras (compras, transferências)', max_digits=10, verbose_name='Quantidade Prevista Entrada')),
                ('quantidade_prevista_saida', models.DecimalField(decimal_places=3, default=0, help_text='Quantidade esperada em saídas futuras (vendas, transferências)', max_digits=10, verbose_name='Quantidade Prevista Saída')),
                ('localizacao_interna', models.CharField(blank=True, help_text='Ex: Prateleira A-3, Setor B, Corredor 5', max_length=100, null=True, verbose_name='Localização Interna')),
                ('valor_custo_medio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo Médio')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Valor Total')),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0, help_text='Alerta quando estoque ficar abaixo deste valor', max_digits=10, verbose_name='Estoque Mínimo')),
                ('estoque_maximo', models.DecimalField(decimal_places=3, default=0, help_text='Sugestão de compra quando estoque ficar abaixo deste valor', max_digits=10, verbose_name='Estoque Máximo')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Usuário que excluiu o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques', to='tenants.empresa', verbose_name='Empresa')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques', to='estoque.location', verbose_name='Location')),
                ('owner', models.ForeignKey(blank=True, help_text='Proprietário do registro (pode ser diferente de quem criou)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques', to='cadastros.produto', verbose_name='Produto')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que fez a última modificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro', verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica se o registro foi excluído (soft delete)', verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi excluído', null=True, verbose_name='Data de Exclusão')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('TRANSFERENCIA', 'Transferência'), ('AJUSTE', 'Ajuste'), ('RESERVA', 'Reserva'), ('CANCELAMENTO_RESERVA', 'Cancelamento de Reserva')], max_length=20, verbose_name='Tipo')),
                ('origem', models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda'), ('DEVOLUCAO', 'Devolução'), ('TRANSFERENCIA', 'Transferência entre Locations'), ('AJUSTE_MANUAL', 'Ajuste Manual'), ('PERDA', 'Perda/Danificação'), ('RESERVA', 'Reserva de Venda'), ('CANCELAMENTO_NF', 'Cancelamento de Nota Fiscal'), ('RETORNO_NF', 'Retorno de Nota Fiscal')], max_length=20, verbose_name='Origem')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('REVERTIDA', 'Revertida')], default='CONFIRMADA', max_length=20, verbose_name='Status')),
                ('quantidade', models.DecimalField(decimal_places=3, help_text='Quantidade sempre positiva. Use o campo tipo para indicar entrada/saída.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantidade')),
                ('quantidade_anterior', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantidade Anterior')),
                ('quantidade_posterior', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantidade Posterior')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('documento_referencia', models.CharField(blank=True, help_text='Ex: NF-001234, Pedido-567', max_length=50, null=True, verbose_name='Documento de Referência')),
                ('numero_nota_fiscal', models.CharField(blank=True, help_text='Número da NF relacionada (para cancelamento/retorno)', max_length=50, null=True, verbose_name='Número da Nota Fiscal')),
                ('serie_nota_fiscal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Série da Nota Fiscal')),
                ('motivo_cancelamento', models.TextField(blank=True, help_text='Motivo do cancelamento ou retorno', null=True, verbose_name='Motivo do Cancelamento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
                ('data_prevista', models.DateTimeField(blank=True, help_text='Data prevista para movimentação (para previsões)', null=True, verbose_name='Data Prevista')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Usuário que excluiu o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.estoque', verbose_name='Estoque')),
                ('location_destino', models.ForeignKey(blank=True, help_text='Location de destino (para transferências)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_destino', to='estoque.location', verbose_name='Location Destino')),
                ('location_origem', models.ForeignKey(blank=True, help_text='Location de origem (para transferências)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_origem', to='estoque.location', verbose_name='Location Origem')),
                ('movimentacao_original', models.ForeignKey(blank=True, help_text='Movimentação que foi cancelada/revertida', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_reversas', to='estoque.movimentacaoestoque', verbose_name='Movimentação Original')),
                ('owner', models.ForeignKey(blank=True, help_text='Proprietário do registro (pode ser diferente de quem criou)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que fez a última modificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
                'indexes': [models.Index(fields=['estoque', 'data_movimentacao'], name='estoque_mov_estoque_a2043f_idx'), models.Index(fields=['tipo', 'data_movimentacao'], name='estoque_mov_tipo_c8501c_idx'), models.Index(fields=['origem', 'status'], name='estoque_mov_origem_69a415_idx'), models.Index(fields=['numero_nota_fiscal', 'serie_nota_fiscal'], name='estoque_mov_numero__9ed4b4_idx'), models.Index(fields=['location_origem', 'location_destino'], name='estoque_mov_locatio_318258_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['empresa', 'is_active'], name='estoque_loc_empresa_41c149_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['tipo', 'is_active'], name='estoque_loc_tipo_ce5a07_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['codigo'], name='estoque_loc_codigo_7ae515_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['filial', 'is_active'], name='estoque_loc_filial__bbc4de_idx'),
        ),
        migrations.AddIndex(
            model_name='estoque',
            index=models.Index(fields=['empresa', 'location'], name='estoque_est_empresa_6a05f1_idx'),
        ),
        migrations.AddIndex(
            model_name='estoque',
            index=models.Index(fields=['produto', 'location'], name='estoque_est_produto_1ceed9_idx'),
        ),
        migrations.AddIndex(
            model_name='estoque',
            index=models.Index(fields=['location', 'is_deleted'], name='estoque_est_locatio_1ca8ee_idx'),
        ),
        migrations.AddIndex(
            model_name='estoque',
            index=models.Index(fields=['empresa', 'produto'], name='estoque_est_empresa_4488bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='estoque',
            unique_together={('produto', 'location')},
        ),
    ]
