# Generated by Django 4.2.26 on 2025-12-31 18:31

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro', verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica se o registro foi excluído (soft delete)', verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi excluído', null=True, verbose_name='Data de Exclusão')),
                ('tipo', models.CharField(choices=[('SOFT', 'Soft Reservation'), ('HARD', 'Hard Reservation')], default='SOFT', help_text='SOFT: não bloqueia estoque. HARD: bloqueia estoque físico.', max_length=10, verbose_name='Tipo de Reserva')),
                ('origem', models.CharField(choices=[('VENDA', 'Venda'), ('ECOMMERCE', 'E-commerce'), ('PEDIDO', 'Pedido'), ('COTACAO', 'Cotação'), ('OUTRO', 'Outro')], help_text='Origem da reserva (venda, e-commerce, etc.)', max_length=20, verbose_name='Origem')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('EXPIRADA', 'Expirada')], default='ATIVA', max_length=20, verbose_name='Status')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantidade Reservada')),
                ('data_expiracao', models.DateTimeField(blank=True, help_text='Data/hora em que a reserva expira (para SOFT reservations)', null=True, verbose_name='Data de Expiração')),
                ('documento_referencia', models.CharField(blank=True, help_text='Ex: ID do Pedido de Venda, ID do Carrinho', max_length=100, null=True, verbose_name='Documento de Referência')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Usuário que excluiu o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('estoque', models.ForeignKey(help_text='Estoque específico onde a reserva foi feita', on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='estoque.estoque', verbose_name='Estoque')),
                ('owner', models.ForeignKey(blank=True, help_text='Proprietário do registro (pode ser diferente de quem criou)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que fez a última modificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Reserva de Estoque',
                'verbose_name_plural': 'Reservas de Estoque',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['estoque', 'status'], name='estoque_res_estoque_0d61bb_idx'), models.Index(fields=['tipo', 'status'], name='estoque_res_tipo_ec898d_idx'), models.Index(fields=['data_expiracao', 'status'], name='estoque_res_data_ex_2db1c0_idx'), models.Index(fields=['origem', 'status'], name='estoque_res_origem_9f778c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrevisaoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro', verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica se o registro foi excluído (soft delete)', verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi excluído', null=True, verbose_name='Data de Exclusão')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('TRANSFERENCIA', 'Transferência')], max_length=20, verbose_name='Tipo de Movimentação')),
                ('origem', models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda'), ('TRANSFERENCIA', 'Transferência entre Locations'), ('PRODUCAO', 'Produção'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Origem')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('REALIZADA', 'Realizada')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantidade')),
                ('data_prevista', models.DateTimeField(help_text='Data/hora prevista para a movimentação', verbose_name='Data Prevista')),
                ('valor_unitario_previsto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Unitário Previsto')),
                ('documento_referencia', models.CharField(blank=True, help_text='Ex: ID do Pedido de Compra, ID do Pedido de Venda', max_length=100, null=True, verbose_name='Documento de Referência')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Usuário que excluiu o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('estoque', models.ForeignKey(help_text='Estoque que será afetado pela movimentação', on_delete=django.db.models.deletion.CASCADE, related_name='previsoes', to='estoque.estoque', verbose_name='Estoque')),
                ('location_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previsoes_destino', to='estoque.location', verbose_name='Location de Destino')),
                ('location_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previsoes_origem', to='estoque.location', verbose_name='Location de Origem')),
                ('movimentacao_realizada', models.ForeignKey(blank=True, help_text='Movimentação que realizou esta previsão', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previsao_origem', to='estoque.movimentacaoestoque', verbose_name='Movimentação Realizada')),
                ('owner', models.ForeignKey(blank=True, help_text='Proprietário do registro (pode ser diferente de quem criou)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que fez a última modificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Previsão de Movimentação',
                'verbose_name_plural': 'Previsões de Movimentação',
                'ordering': ['data_prevista'],
                'indexes': [models.Index(fields=['estoque', 'status'], name='estoque_pre_estoque_9267a5_idx'), models.Index(fields=['tipo', 'status'], name='estoque_pre_tipo_dc0485_idx'), models.Index(fields=['data_prevista', 'status'], name='estoque_pre_data_pr_a0a9c2_idx'), models.Index(fields=['origem', 'status'], name='estoque_pre_origem_5229da_idx')],
            },
        ),
    ]
