# Generated by Django 4.2.26 on 2025-12-31 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_last_backup_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estoque', '0002_reservaestoque_previsaomovimentacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoFilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro', verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica se o registro foi excluído (soft delete)', verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi excluído', null=True, verbose_name='Data de Exclusão')),
                ('nome', models.CharField(help_text='Ex: Região Sul, Região Norte, Centro de Distribuição', max_length=255, verbose_name='Nome do Grupo')),
                ('codigo', models.CharField(help_text='Código único para identificar o grupo', max_length=50, unique=True, verbose_name='Código')),
                ('regra_alocacao', models.CharField(choices=[('PROXIMIDADE', 'Proximidade'), ('ESTOQUE_DISPONIVEL', 'Maior Estoque Disponível'), ('CUSTO_MENOR', 'Menor Custo'), ('ROTACAO', 'Maior Rotação'), ('MANUAL', 'Manual')], default='ESTOQUE_DISPONIVEL', help_text='Regra usada para determinar melhor filial para atendimento', max_length=30, verbose_name='Regra de Alocação')),
                ('permite_fulfillment_cruzado', models.BooleanField(default=True, help_text='Se permite atender pedido de uma filial com estoque de outra', verbose_name='Permite Fulfillment Cruzado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Usuário que excluiu o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_filiais', to='tenants.empresa', verbose_name='Empresa')),
                ('filiais', models.ManyToManyField(help_text='Filiais que pertencem a este grupo', related_name='grupos', to='tenants.filial', verbose_name='Filiais')),
                ('owner', models.ForeignKey(blank=True, help_text='Proprietário do registro (pode ser diferente de quem criou)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que fez a última modificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Grupo de Filiais',
                'verbose_name_plural': 'Grupos de Filiais',
                'ordering': ['empresa', 'nome'],
                'indexes': [models.Index(fields=['empresa', 'is_active'], name='estoque_gru_empresa_6cab5d_idx'), models.Index(fields=['codigo'], name='estoque_gru_codigo_59471f_idx')],
            },
        ),
    ]
