# Generated by Django 4.2.26 on 2025-11-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('codigo_cadastro', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código Cadastro')),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2, verbose_name='Tipo de Pessoa')),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('nome_completo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Completo')),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('contribuinte', models.BooleanField(default=True, verbose_name='Contribuinte ICMS')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('letra', models.CharField(blank=True, max_length=2, null=True, verbose_name='Letra')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='SC', max_length=2)),
                ('cep', models.CharField(default='99999-999', max_length=9)),
                ('nome_contato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Contato')),
                ('telefone_fixo', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone Fixo')),
                ('telefone_celular', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('comissoes', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Comissão (%)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo_produto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('valor_custo', models.DecimalField(decimal_places=2, default=0.0, help_text='Custo de aquisição do produto.', max_digits=10)),
                ('valor_venda', models.DecimalField(decimal_places=2, default=0.0, help_text='Preço de venda sugerido.', max_digits=10)),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Kilograma'), ('LT', 'Litro'), ('M2', 'Metro Quadrado')], default='UN', max_length=10)),
                ('peso_liquido', models.DecimalField(blank=True, decimal_places=3, help_text='Peso líquido em Kg.', max_digits=10, null=True)),
                ('peso_bruto', models.DecimalField(blank=True, decimal_places=3, help_text='Peso bruto em Kg (incluindo embalagem).', max_digits=10, null=True)),
                ('codigo_ncm', models.CharField(help_text='Nomenclatura Comum do Mercosul.', max_length=10)),
                ('cfop_interno', models.CharField(blank=True, help_text='CFOP para vendas internas.', max_length=4, null=True)),
                ('origem_mercadoria', models.CharField(choices=[('0', 'Nacional'), ('1', 'Estrangeira - Importação Direta'), ('2', 'Estrangeira - Adquirida no Mercado Interno')], default='0', help_text='CST de Origem.', max_length=2)),
                ('cst_icms', models.CharField(blank=True, help_text='CST/CSOSN do ICMS.', max_length=3, null=True)),
                ('aliquota_icms', models.DecimalField(decimal_places=2, default=0.0, help_text='Alíquota ICMS (%)', max_digits=5)),
                ('aliquota_ipi', models.DecimalField(decimal_places=2, default=0.0, help_text='Alíquota IPI (%)', max_digits=5)),
                ('codigo_di', models.CharField(blank=True, help_text='Número de Declaração de Importação (DI) mais recente.', max_length=20, null=True)),
                ('incoterm', models.CharField(blank=True, help_text='Último Incoterm utilizado (e.g., FOB, CIF).', max_length=10, null=True)),
                ('moeda_negociacao', models.CharField(choices=[('BRL', 'Real'), ('USD', 'Dólar Americano'), ('EUR', 'Euro')], default='BRL', help_text='Moeda de negociação padrão.', max_length=3)),
                ('aliquota_ii', models.DecimalField(decimal_places=2, default=0.0, help_text='Alíquota de Imposto de Importação (II) (%)', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('codigo_servico', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('valor_base', models.DecimalField(decimal_places=2, help_text='Valor base de venda do serviço.', max_digits=10)),
                ('tipo_contrato', models.CharField(choices=[('Mensal', 'Mensal'), ('Anual', 'Anual'), ('Projeto', 'Por Projeto'), ('Avulso', 'Avulso')], default='Avulso', max_length=50)),
                ('prazo_execucao', models.IntegerField(blank=True, help_text='Prazo em dias úteis para execução, se aplicável.', null=True)),
                ('valor_impostos_estimado', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Estimativa de impostos incidentes.', max_digits=10, null=True)),
                ('codigo_ncm', models.CharField(blank=True, help_text='Código NCM para classificação fiscal (se aplicável).', max_length=10, null=True)),
                ('cfop', models.CharField(blank=True, help_text='CFOP - Código Fiscal de Operações e Prestações.', max_length=4, null=True)),
                ('tributacao_pis', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Alíquota PIS (%)', max_digits=5, null=True)),
                ('tributacao_cofins', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Alíquota COFINS (%)', max_digits=5, null=True)),
                ('icms_tributado', models.BooleanField(default=False, help_text='O serviço incide ICMS?')),
            ],
        ),
    ]
