# Generated by Django 4.2.26 on 2025-11-13 02:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('codigo_conta', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código da Conta')),
                ('numero_documento', models.CharField(max_length=50, unique=True, verbose_name='Número do Documento')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Total')),
                ('valor_recebido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Recebido')),
                ('valor_pendente', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Valor Pendente')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Parcial', 'Parcialmente Pago'), ('Pago', 'Pago'), ('Cancelado', 'Cancelado'), ('Vencido', 'Vencido')], default='Pendente', max_length=20, verbose_name='Status')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('Dinheiro', 'Dinheiro'), ('PIX', 'PIX'), ('Boleto', 'Boleto'), ('Cartão Crédito', 'Cartão de Crédito'), ('Cartão Débito', 'Cartão de Débito'), ('Transferência', 'Transferência Bancária'), ('Cheque', 'Cheque')], max_length=20, null=True, verbose_name='Forma de Pagamento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(limit_choices_to={'tipo': 'PJ'}, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='cadastros.pessoa', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['-data_vencimento', '-codigo_conta'],
                'indexes': [models.Index(fields=['cliente', 'status'], name='cadastros_c_cliente_f850ad_idx'), models.Index(fields=['data_vencimento', 'status'], name='cadastros_c_data_ve_45c736_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('codigo_conta', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código da Conta')),
                ('numero_documento', models.CharField(max_length=50, unique=True, verbose_name='Número do Documento')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Total')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Pago')),
                ('valor_pendente', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Valor Pendente')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Parcial', 'Parcialmente Pago'), ('Pago', 'Pago'), ('Cancelado', 'Cancelado'), ('Vencido', 'Vencido')], default='Pendente', max_length=20, verbose_name='Status')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('Dinheiro', 'Dinheiro'), ('PIX', 'PIX'), ('Boleto', 'Boleto'), ('Cartão Crédito', 'Cartão de Crédito'), ('Cartão Débito', 'Cartão de Débito'), ('Transferência', 'Transferência Bancária'), ('Cheque', 'Cheque')], max_length=20, null=True, verbose_name='Forma de Pagamento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('fornecedor', models.ForeignKey(limit_choices_to={'tipo': 'PJ'}, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='cadastros.pessoa', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['-data_vencimento', '-codigo_conta'],
                'indexes': [models.Index(fields=['fornecedor', 'status'], name='cadastros_c_fornece_13b663_idx'), models.Index(fields=['data_vencimento', 'status'], name='cadastros_c_data_ve_81b596_idx')],
            },
        ),
    ]
