# Generated by Django 4.2.26 on 2025-11-15 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('cadastros', '0002_contareceber_contapagar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AddField(
            model_name='contapagar',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para dados compartilhados entre todas as empresas', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='tenants.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para dados compartilhados entre todas as filiais', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='tenants.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para dados compartilhados entre todas as empresas', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='tenants.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para dados compartilhados entre todas as filiais', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='tenants.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para dados compartilhados entre todas as empresas', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pessoas', to='tenants.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para dados compartilhados entre todas as filiais', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pessoas', to='tenants.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='produto',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para dados compartilhados entre todas as empresas', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='tenants.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='produto',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para dados compartilhados entre todas as filiais', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='tenants.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='servico',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para dados compartilhados entre todas as empresas', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='tenants.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='servico',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para dados compartilhados entre todas as filiais', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='tenants.filial', verbose_name='Filial'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['empresa', 'filial'], name='cadastros_c_empresa_e7046c_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['empresa'], name='cadastros_c_empresa_d5ffd3_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['filial'], name='cadastros_c_filial__5a9b74_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['empresa', 'filial'], name='cadastros_c_empresa_009f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['empresa'], name='cadastros_c_empresa_c6fb94_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['filial'], name='cadastros_c_filial__12ddf7_idx'),
        ),
        migrations.AddIndex(
            model_name='pessoa',
            index=models.Index(fields=['empresa', 'filial'], name='cadastros_p_empresa_b6c651_idx'),
        ),
        migrations.AddIndex(
            model_name='pessoa',
            index=models.Index(fields=['empresa'], name='cadastros_p_empresa_b5f890_idx'),
        ),
        migrations.AddIndex(
            model_name='pessoa',
            index=models.Index(fields=['filial'], name='cadastros_p_filial__d50373_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['empresa', 'filial'], name='cadastros_p_empresa_8e3a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['empresa'], name='cadastros_p_empresa_6681ba_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['filial'], name='cadastros_p_filial__fe3b05_idx'),
        ),
        migrations.AddIndex(
            model_name='servico',
            index=models.Index(fields=['empresa', 'filial'], name='cadastros_s_empresa_da7fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='servico',
            index=models.Index(fields=['empresa'], name='cadastros_s_empresa_326f36_idx'),
        ),
        migrations.AddIndex(
            model_name='servico',
            index=models.Index(fields=['filial'], name='cadastros_s_filial__cea10f_idx'),
        ),
    ]
