# Generated by Django 5.2.7 on 2025-10-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='valor',
        ),
        migrations.AddField(
            model_name='servico',
            name='cfop',
            field=models.CharField(blank=True, help_text='CFOP - Código Fiscal de Operações e Prestações.', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='codigo_ncm',
            field=models.CharField(blank=True, help_text='Código NCM para classificação fiscal (se aplicável).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='icms_tributado',
            field=models.BooleanField(default=False, help_text='O serviço incide ICMS?'),
        ),
        migrations.AddField(
            model_name='servico',
            name='prazo_execucao',
            field=models.IntegerField(blank=True, help_text='Prazo em dias úteis para execução, se aplicável.', null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='tipo_contrato',
            field=models.CharField(choices=[('Mensal', 'Mensal'), ('Anual', 'Anual'), ('Projeto', 'Por Projeto'), ('Avulso', 'Avulso')], default='Avulso', max_length=50),
        ),
        migrations.AddField(
            model_name='servico',
            name='tributacao_cofins',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Alíquota COFINS (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='tributacao_pis',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Alíquota PIS (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='valor_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor base de venda do serviço.', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='valor_impostos_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Estimativa de impostos incidentes.', max_digits=10, null=True),
        ),
    ]
