# Generated by Django 5.2.7 on 2025-10-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_servico_valor_servico_cfop_servico_codigo_ncm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo_produto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('valor_custo', models.DecimalField(decimal_places=2, default=0.0, help_text='Custo de aquisição do produto.', max_digits=10)),
                ('valor_venda', models.DecimalField(decimal_places=2, default=0.0, help_text='Preço de venda sugerido.', max_digits=10)),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Kilograma'), ('LT', 'Litro'), ('M2', 'Metro Quadrado')], default='UN', max_length=10)),
                ('peso_liquido', models.DecimalField(blank=True, decimal_places=3, help_text='Peso líquido em Kg.', max_digits=10, null=True)),
                ('peso_bruto', models.DecimalField(blank=True, decimal_places=3, help_text='Peso bruto em Kg (incluindo embalagem).', max_digits=10, null=True)),
                ('codigo_ncm', models.CharField(help_text='Nomenclatura Comum do Mercosul.', max_length=10)),
                ('cfop_interno', models.CharField(blank=True, help_text='CFOP para vendas internas.', max_length=4, null=True)),
                ('origem_mercadoria', models.CharField(choices=[('0', 'Nacional'), ('1', 'Estrangeira - Importação Direta'), ('2', 'Estrangeira - Adquirida no Mercado Interno')], default='0', help_text='CST de Origem.', max_length=2)),
                ('cst_icms', models.CharField(blank=True, help_text='CST/CSOSN do ICMS.', max_length=3, null=True)),
                ('aliquota_icms', models.DecimalField(decimal_places=2, default=0.0, help_text='Alíquota ICMS (%)', max_digits=5)),
                ('aliquota_ipi', models.DecimalField(decimal_places=2, default=0.0, help_text='Alíquota IPI (%)', max_digits=5)),
                ('codigo_di', models.CharField(blank=True, help_text='Número de Declaração de Importação (DI) mais recente.', max_length=20, null=True)),
                ('incoterm', models.CharField(blank=True, help_text='Último Incoterm utilizado (e.g., FOB, CIF).', max_length=10, null=True)),
                ('moeda_negociacao', models.CharField(choices=[('BRL', 'Real'), ('USD', 'Dólar Americano'), ('EUR', 'Euro')], default='BRL', help_text='Moeda de negociação padrão.', max_length=3)),
                ('aliquota_ii', models.DecimalField(decimal_places=2, default=0.0, help_text='Alíquota de Imposto de Importação (II) (%)', max_digits=5)),
            ],
        ),
    ]
