# Generated by Django 4.2.26 on 2025-11-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_pessoa_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
