# Generated by Django 4.2.27 on 2025-12-21 19:07
# Migration segura que apenas atualiza o estado do Django sem modificar o banco

from django.db import migrations, models


def noop(apps, schema_editor):
    """Não faz nada - os campos já existem no banco"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_created_at_updated_at'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Não modifica o banco, os campos já existem
            state_operations=[
                migrations.AlterField(
                    model_name='tenant',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação'),
                ),
                migrations.AlterField(
                    model_name='tenant',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro', verbose_name='Data de Atualização'),
                ),
            ],
        ),
    ]
