# Generated by Django 4.2.27 on 2025-12-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenant_created_at_alter_tenant_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='last_backup_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora do último backup manual realizado', null=True, verbose_name='Último Backup Manual'),
        ),
    ]
