# Generated by Django 4.2.26 on 2025-12-25 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0004_tenant_last_backup_at'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro', verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica se o registro foi excluído (soft delete)', verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi excluído', null=True, verbose_name='Data de Exclusão')),
                ('name', models.CharField(help_text='Nome do papel (ex: "Gerente Financeiro", "Operador de Cadastros")', max_length=100, verbose_name='Nome do Role')),
                ('code', models.CharField(help_text='Código único do role (ex: "gerente_financeiro", "operador_cadastros")', max_length=50, verbose_name='Código')),
                ('description', models.TextField(blank=True, help_text='Descrição do que este role permite fazer', verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_system', models.BooleanField(default=False, help_text='Roles do sistema (admin, manager, user, viewer) não podem ser editados', verbose_name='Role do Sistema')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Usuário que excluiu o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('owner', models.ForeignKey(blank=True, help_text='Proprietário do registro (pode ser diferente de quem criou)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='tenants.tenant', verbose_name='Tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que fez a última modificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Role Customizado',
                'verbose_name_plural': 'Roles Customizados',
            },
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro', verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica se o registro foi excluído (soft delete)', verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi excluído', null=True, verbose_name='Data de Exclusão')),
                ('module', models.CharField(help_text='Código do módulo (ex: "cadastros", "financeiro", "faturamento")', max_length=50, verbose_name='Módulo')),
                ('module_display', models.CharField(blank=True, help_text='Nome exibido do módulo (ex: "Cadastros", "Financeiro")', max_length=100, verbose_name='Nome do Módulo')),
                ('actions', models.JSONField(default=list, help_text='Lista de ações permitidas neste módulo (ex: ["view", "add", "change"])', verbose_name='Ações Permitidas')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Usuário que excluiu o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('owner', models.ForeignKey(blank=True, help_text='Proprietário do registro (pode ser diferente de quem criou)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='accounts.customrole', verbose_name='Role')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que fez a última modificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Permissão de Módulo',
                'verbose_name_plural': 'Permissões de Módulos',
                'indexes': [models.Index(fields=['role', 'module'], name='accounts_mo_role_id_8b7fc1_idx')],
                'unique_together': {('role', 'module')},
            },
        ),
        migrations.AddIndex(
            model_name='customrole',
            index=models.Index(fields=['tenant', 'is_active'], name='accounts_cu_tenant__1afc61_idx'),
        ),
        migrations.AddIndex(
            model_name='customrole',
            index=models.Index(fields=['tenant', 'code'], name='accounts_cu_tenant__1943a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customrole',
            unique_together={('tenant', 'code')},
        ),
    ]
