# Generated by Django 4.2.26 on 2025-12-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customrole_modulepermission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantmembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gerente'), ('user', 'Usuário'), ('viewer', 'Visualizador')], default='user', help_text='Papel do usuário (roles do sistema: admin, manager, user, viewer ou código de role customizado)', max_length=50, verbose_name='Papel'),
        ),
    ]
