# Generated by Django 4.2.27 on 2026-01-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_increase_role_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='current_empresa',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='current_filial',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_empresa_id',
            field=models.IntegerField(blank=True, help_text='ID da empresa no schema do tenant', null=True, verbose_name='ID da Empresa Atual'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_filial_id',
            field=models.IntegerField(blank=True, help_text='ID da filial no schema do tenant', null=True, verbose_name='ID da Filial Atual'),
        ),
    ]
