# Generated by Django 4.2.27 on 2026-01-11 18:06

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faturamento', '0001_initial'),
        ('cadastros', '0003_remove_contareceber_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estoque', '0003_grupofilial'),
        ('tenants', '0004_tenant_last_backup_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro', verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica se o registro foi excluído (soft delete)', verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi excluído', null=True, verbose_name='Data de Exclusão')),
                ('numero_pedido', models.CharField(help_text='Número único do pedido (ex: PED-2024-001)', max_length=50, unique=True, verbose_name='Número do Pedido')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('FATURADO', 'Faturado'), ('CANCELADO', 'Cancelado'), ('ENTREGUE', 'Entregue')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Soma dos valores dos itens', max_digits=10, verbose_name='Valor Total')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Desconto')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Frete')),
                ('data_pedido', models.DateTimeField(verbose_name='Data do Pedido')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('data_faturamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Faturamento')),
                ('data_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('PIX', 'PIX'), ('BOLETO', 'Boleto'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência')], max_length=50, null=True, verbose_name='Forma de Pagamento')),
                ('numero_parcelas', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Parcelas')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(limit_choices_to={'tipo': 'PJ'}, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_venda', to='cadastros.pessoa', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Usuário que excluiu o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_venda', to='tenants.empresa', verbose_name='Empresa')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_venda', to='tenants.filial', verbose_name='Filial')),
                ('nota_fiscal', models.ForeignKey(blank=True, help_text='NF-e gerada a partir deste pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='faturamento.notafiscaleletronica', verbose_name='Nota Fiscal')),
                ('owner', models.ForeignKey(blank=True, help_text='Proprietário do registro (pode ser diferente de quem criou)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que fez a última modificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Pedido de Venda',
                'verbose_name_plural': 'Pedidos de Venda',
                'ordering': ['-data_pedido', '-numero_pedido'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro', verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica se o registro foi excluído (soft delete)', verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi excluído', null=True, verbose_name='Data de Exclusão')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Quantidade × Valor Unitário', max_digits=10, verbose_name='Valor Total')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Desconto')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Usuário que excluiu o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('location', models.ForeignKey(blank=True, help_text='Location de onde o produto será retirado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='estoque.location', verbose_name='Location')),
                ('movimentacao_estoque', models.ForeignKey(blank=True, help_text='Movimentação de estoque gerada quando o pedido foi faturado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pedido', to='estoque.movimentacaoestoque', verbose_name='Movimentação de Estoque')),
                ('owner', models.ForeignKey(blank=True, help_text='Proprietário do registro (pode ser diferente de quem criou)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.pedidovenda', verbose_name='Pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='cadastros.produto', verbose_name='Produto')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que fez a última modificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'ordering': ['pedido', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='pedidovenda',
            index=models.Index(fields=['cliente', 'status'], name='vendas_pedi_cliente_a3a031_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidovenda',
            index=models.Index(fields=['empresa', 'filial'], name='vendas_pedi_empresa_cb7fe3_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidovenda',
            index=models.Index(fields=['status', 'data_pedido'], name='vendas_pedi_status_5e3bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidovenda',
            index=models.Index(fields=['numero_pedido'], name='vendas_pedi_numero__80cc58_idx'),
        ),
        migrations.AddIndex(
            model_name='itempedido',
            index=models.Index(fields=['pedido', 'produto'], name='vendas_item_pedido__7cf9c3_idx'),
        ),
        migrations.AddIndex(
            model_name='itempedido',
            index=models.Index(fields=['location'], name='vendas_item_locatio_648a8d_idx'),
        ),
    ]
