# Generated by Django 4.2.26 on 2026-01-04 02:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_tenant_last_backup_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro', verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica se o registro foi excluído (soft delete)', verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi excluído', null=True, verbose_name='Data de Exclusão')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('codigo', models.SlugField(help_text='Código único do template (ex: estoque-por-location)', unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Código')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('modulo', models.CharField(help_text='Módulo do sistema (ex: estoque, faturamento)', max_length=50, verbose_name='Módulo')),
                ('tipo_relatorio', models.CharField(help_text='Tipo específico do relatório (ex: estoque-por-location)', max_length=100, verbose_name='Tipo de Relatório')),
                ('template_customizado', models.BooleanField(default=False, help_text='Se True, usa template_html do banco. Se False, busca arquivo padrão.', verbose_name='Template Customizado')),
                ('template_arquivo', models.CharField(blank=True, help_text='Caminho do arquivo template padrão (ex: reports/modules/estoque/estoque_por_location.html)', max_length=200, verbose_name='Arquivo do Template')),
                ('template_html', models.TextField(blank=True, help_text='HTML customizado do template (usado se template_customizado=True)', verbose_name='HTML do Template')),
                ('template_css', models.TextField(blank=True, help_text='CSS adicional para o template', verbose_name='CSS Customizado')),
                ('incluir_logo', models.BooleanField(default=True, verbose_name='Incluir Logo')),
                ('incluir_dados_empresa', models.BooleanField(default=True, verbose_name='Incluir Dados da Empresa')),
                ('orientacao', models.CharField(choices=[('portrait', 'Retrato'), ('landscape', 'Paisagem')], default='portrait', max_length=10, verbose_name='Orientação')),
                ('variaveis_disponiveis', models.JSONField(blank=True, default=dict, help_text='Variáveis que podem ser usadas no template (JSON)', verbose_name='Variáveis Disponíveis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_default', models.BooleanField(default=False, help_text='Template padrão para este tipo de relatório', verbose_name='Template Padrão')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Usuário que excluiu o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('empresa', models.ForeignKey(blank=True, help_text='Se especificado, template é específico desta empresa', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.empresa', verbose_name='Empresa')),
                ('owner', models.ForeignKey(blank=True, help_text='Proprietário do registro (pode ser diferente de quem criou)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('tenant', models.ForeignKey(blank=True, help_text='Se especificado, template é específico deste tenant', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que fez a última modificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Template de Relatório',
                'verbose_name_plural': 'Templates de Relatórios',
                'ordering': ['modulo', 'tipo_relatorio', 'nome'],
                'indexes': [models.Index(fields=['modulo', 'tipo_relatorio'], name='reports_rep_modulo_68a8a5_idx'), models.Index(fields=['codigo'], name='reports_rep_codigo_5cdb42_idx'), models.Index(fields=['tenant', 'empresa'], name='reports_rep_tenant__af7bf9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro', verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica se o registro foi excluído (soft delete)', verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi excluído', null=True, verbose_name='Data de Exclusão')),
                ('logo_url', models.URLField(blank=True, help_text='URL externa do logo', verbose_name='URL do Logo')),
                ('logo_upload', models.ImageField(blank=True, help_text='Upload de logo (sobrescreve logo_url se especificado)', null=True, upload_to='reports/logos/', verbose_name='Logo Upload')),
                ('nome_empresa', models.CharField(blank=True, help_text='Se vazio, usa nome da empresa do modelo', max_length=200, verbose_name='Nome da Empresa')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=50, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('cnpj', models.CharField(blank=True, max_length=20, verbose_name='CNPJ')),
                ('formato_padrao', models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML'), ('xlsx', 'Excel')], default='pdf', max_length=10, verbose_name='Formato Padrão')),
                ('email_destinatario_padrao', models.EmailField(blank=True, max_length=254, verbose_name='Email Destinatário Padrão')),
                ('assunto_padrao', models.CharField(blank=True, max_length=200, verbose_name='Assunto Padrão')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Usuário que excluiu o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('empresa', models.ForeignKey(blank=True, help_text='Se None, configuração é para todo o tenant', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.empresa', verbose_name='Empresa')),
                ('owner', models.ForeignKey(blank=True, help_text='Proprietário do registro (pode ser diferente de quem criou)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que fez a última modificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Configuração de Relatório',
                'verbose_name_plural': 'Configurações de Relatórios',
                'indexes': [models.Index(fields=['tenant', 'empresa'], name='reports_rep_tenant__3be3d8_idx')],
                'unique_together': {('tenant', 'empresa')},
            },
        ),
    ]
