# Generated by Django 4.2.27 on 2026-01-11 18:06

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faturamento', '0001_initial'),
        ('cadastros', '0003_remove_contareceber_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0004_tenant_last_backup_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro', verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica se o registro foi excluído (soft delete)', verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi excluído', null=True, verbose_name='Data de Exclusão')),
                ('nosso_numero', models.CharField(help_text='Número de controle do boleto', max_length=20, verbose_name='Nosso Número')),
                ('codigo_barras', models.CharField(max_length=44, verbose_name='Código de Barras')),
                ('linha_digitavel', models.CharField(max_length=48, verbose_name='Linha Digitável')),
                ('gateway', models.CharField(choices=[('gerencianet', 'Gerencianet'), ('pagseguro', 'PagSeguro'), ('banco_brasil', 'Banco do Brasil'), ('bradesco', 'Bradesco'), ('itaú', 'Itaú')], help_text='Gateway usado para gerar o boleto', max_length=50, verbose_name='Gateway')),
                ('gateway_id', models.CharField(blank=True, help_text='ID do boleto no gateway', max_length=255, null=True, verbose_name='ID no Gateway')),
                ('status', models.CharField(choices=[('GERADO', 'Gerado'), ('REGISTRADO', 'Registrado'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado'), ('VENCIDO', 'Vencido')], default='GERADO', max_length=20, verbose_name='Status')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('pdf_path', models.FileField(blank=True, null=True, upload_to='boletos/', verbose_name='PDF do Boleto')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
                'ordering': ['-data_vencimento', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro', verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica se o registro foi excluído (soft delete)', verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi excluído', null=True, verbose_name='Data de Exclusão')),
                ('codigo_conta', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código da Conta')),
                ('numero_documento', models.CharField(max_length=50, unique=True, verbose_name='Número do Documento')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Total')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Pago')),
                ('valor_pendente', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Valor Pendente')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Parcial', 'Parcialmente Pago'), ('Pago', 'Pago'), ('Cancelado', 'Cancelado'), ('Vencido', 'Vencido')], default='Pendente', max_length=20, verbose_name='Status')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('Dinheiro', 'Dinheiro'), ('PIX', 'PIX'), ('Boleto', 'Boleto'), ('Cartão Crédito', 'Cartão de Crédito'), ('Cartão Débito', 'Cartão de Débito'), ('Transferência', 'Transferência Bancária'), ('Cheque', 'Cheque')], max_length=20, null=True, verbose_name='Forma de Pagamento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['-data_vencimento', '-codigo_conta'],
            },
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro', verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica se o registro foi excluído (soft delete)', verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi excluído', null=True, verbose_name='Data de Exclusão')),
                ('codigo_conta', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código da Conta')),
                ('numero_documento', models.CharField(max_length=50, unique=True, verbose_name='Número do Documento')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Total')),
                ('valor_recebido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Recebido')),
                ('valor_pendente', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Valor Pendente')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Parcial', 'Parcialmente Pago'), ('Pago', 'Pago'), ('Cancelado', 'Cancelado'), ('Vencido', 'Vencido')], default='Pendente', max_length=20, verbose_name='Status')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('Dinheiro', 'Dinheiro'), ('PIX', 'PIX'), ('Boleto', 'Boleto'), ('Cartão Crédito', 'Cartão de Crédito'), ('Cartão Débito', 'Cartão de Débito'), ('Transferência', 'Transferência Bancária'), ('Cheque', 'Cheque')], max_length=20, null=True, verbose_name='Forma de Pagamento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(limit_choices_to={'tipo': 'PJ'}, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='cadastros.pessoa', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Usuário que excluiu o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('empresa', models.ForeignKey(blank=True, help_text='Deixe em branco para dados compartilhados entre todas as empresas', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='tenants.empresa', verbose_name='Empresa')),
                ('filial', models.ForeignKey(blank=True, help_text='Deixe em branco para dados compartilhados entre todas as filiais', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='tenants.filial', verbose_name='Filial')),
                ('nota_fiscal', models.ForeignKey(blank=True, help_text='Nota Fiscal que originou esta conta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to='faturamento.notafiscaleletronica', verbose_name='Nota Fiscal')),
                ('owner', models.ForeignKey(blank=True, help_text='Proprietário do registro (pode ser diferente de quem criou)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['-data_vencimento', '-codigo_conta'],
            },
        ),
        migrations.CreateModel(
            name='TransacaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro', verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica se o registro foi excluído (soft delete)', verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi excluído', null=True, verbose_name='Data de Exclusão')),
                ('gateway', models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('pagseguro', 'PagSeguro'), ('stripe', 'Stripe'), ('gerencianet', 'Gerencianet'), ('asaas', 'Asaas')], max_length=50, verbose_name='Gateway de Pagamento')),
                ('gateway_transaction_id', models.CharField(help_text='ID retornado pelo gateway', max_length=255, verbose_name='ID da Transação no Gateway')),
                ('metodo_pagamento', models.CharField(choices=[('PIX', 'PIX'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('BOLETO', 'Boleto'), ('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência Bancária')], max_length=20, verbose_name='Método de Pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('valor_liquido', models.DecimalField(decimal_places=2, help_text='Valor após descontar taxas do gateway', max_digits=10, verbose_name='Valor Líquido')),
                ('taxa_gateway', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Taxa do Gateway')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado'), ('ESTORNADO', 'Estornado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('dados_gateway', models.JSONField(blank=True, default=dict, help_text='Dados completos retornados pelo gateway (JSON)', verbose_name='Dados do Gateway')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('conta_receber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='financeiro.contareceber', verbose_name='Conta a Receber')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Usuário que excluiu o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('owner', models.ForeignKey(blank=True, help_text='Proprietário do registro (pode ser diferente de quem criou)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que fez a última modificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Transação de Pagamento',
                'verbose_name_plural': 'Transações de Pagamento',
                'ordering': ['-created_at'],
            },
        ),
    ]
