# Generated by Django 4.2.27 on 2026-01-11 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0003_remove_contareceber_cliente_and_more'),
        ('faturamento', '0002_initial'),
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0001_initial'),
        ('tenants', '0004_tenant_last_backup_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='pedido_venda',
            field=models.ForeignKey(blank=True, help_text='Pedido de venda que originou esta conta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to='vendas.pedidovenda', verbose_name='Pedido de Venda'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que fez a última modificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que excluiu o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para dados compartilhados entre todas as empresas', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='tenants.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para dados compartilhados entre todas as filiais', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='tenants.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='fornecedor',
            field=models.ForeignKey(limit_choices_to={'tipo': 'PJ'}, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='cadastros.pessoa', verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='nota_fiscal_entrada',
            field=models.ForeignKey(blank=True, help_text='Nota Fiscal de entrada que originou esta conta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='faturamento.notafiscaleletronica', verbose_name='Nota Fiscal de Entrada'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Proprietário do registro (pode ser diferente de quem criou)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que fez a última modificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='conta_receber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='financeiro.contareceber', verbose_name='Conta a Receber'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que excluiu o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Proprietário do registro (pode ser diferente de quem criou)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que fez a última modificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
        migrations.AddIndex(
            model_name='transacaopagamento',
            index=models.Index(fields=['conta_receber', 'status'], name='financeiro__conta_r_5efe85_idx'),
        ),
        migrations.AddIndex(
            model_name='transacaopagamento',
            index=models.Index(fields=['gateway', 'gateway_transaction_id'], name='financeiro__gateway_a05e17_idx'),
        ),
        migrations.AddIndex(
            model_name='transacaopagamento',
            index=models.Index(fields=['status', 'data_pagamento'], name='financeiro__status_fd448e_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['cliente', 'status'], name='financeiro__cliente_62fae2_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['data_vencimento', 'status'], name='financeiro__data_ve_cf81e6_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['empresa', 'filial'], name='financeiro__empresa_a84920_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['empresa'], name='financeiro__empresa_57ba2c_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['filial'], name='financeiro__filial__60a8b1_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['nota_fiscal'], name='financeiro__nota_fi_56498a_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['pedido_venda'], name='financeiro__pedido__bc5055_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['fornecedor', 'status'], name='financeiro__fornece_77d83a_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['data_vencimento', 'status'], name='financeiro__data_ve_d25c79_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['empresa', 'filial'], name='financeiro__empresa_83c7d7_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['empresa'], name='financeiro__empresa_e1b8bb_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['filial'], name='financeiro__filial__1666bc_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['nota_fiscal_entrada'], name='financeiro__nota_fi_62ab13_idx'),
        ),
        migrations.AddIndex(
            model_name='boleto',
            index=models.Index(fields=['conta_receber', 'status'], name='financeiro__conta_r_1d5162_idx'),
        ),
        migrations.AddIndex(
            model_name='boleto',
            index=models.Index(fields=['gateway', 'gateway_id'], name='financeiro__gateway_446b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='boleto',
            index=models.Index(fields=['data_vencimento', 'status'], name='financeiro__data_ve_b385fd_idx'),
        ),
    ]
