# Generated by Django 4.2.26 on 2025-11-15 04:33

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro', verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica se o registro foi excluído (soft delete)', verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi excluído', null=True, verbose_name='Data de Exclusão')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ícone (classe CSS)')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Usuário que excluiu o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('owner', models.ForeignKey(blank=True, help_text='Proprietário do registro (pode ser diferente de quem criou)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que fez a última modificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Funcionalidade',
                'verbose_name_plural': 'Funcionalidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro', verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica se o registro foi excluído (soft delete)', verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi excluído', null=True, verbose_name='Data de Exclusão')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Mensal (R$)')),
                ('price_yearly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Anual (R$)')),
                ('max_users', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máximo de Usuários')),
                ('max_empresas', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máximo de Empresas')),
                ('max_filiais', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máximo de Filiais')),
                ('max_storage_gb', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Armazenamento (GB)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_trial', models.BooleanField(default=False, verbose_name='Plano Trial')),
                ('trial_days', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dias de Trial')),
                ('display_order', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Usuário que excluiu o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('features', models.ManyToManyField(blank=True, related_name='plans', to='subscriptions.feature', verbose_name='Funcionalidades')),
                ('owner', models.ForeignKey(blank=True, help_text='Proprietário do registro (pode ser diferente de quem criou)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que fez a última modificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['display_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro', verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica se o registro foi excluído (soft delete)', verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi excluído', null=True, verbose_name='Data de Exclusão')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Ativa'), ('past_due', 'Pagamento Atrasado'), ('canceled', 'Cancelada'), ('expired', 'Expirada')], default='trial', max_length=20, verbose_name='Status')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensal'), ('yearly', 'Anual')], default='monthly', max_length=20, verbose_name='Ciclo de Cobrança')),
                ('current_period_start', models.DateTimeField(verbose_name='Início do Período')),
                ('current_period_end', models.DateTimeField(verbose_name='Fim do Período')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='Cancelar ao Fim do Período')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em')),
                ('payment_gateway_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID no Gateway de Pagamento')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas Internas')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Usuário que excluiu o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('owner', models.ForeignKey(blank=True, help_text='Proprietário do registro (pode ser diferente de quem criou)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan', verbose_name='Plano')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant', verbose_name='Tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que fez a última modificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'current_period_end'], name='subscriptio_status_3d1ac5_idx'), models.Index(fields=['tenant'], name='subscriptio_tenant__cf78d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuotaUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro', verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica se o registro foi excluído (soft delete)', verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi excluído', null=True, verbose_name='Data de Exclusão')),
                ('users_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Usuários')),
                ('empresas_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Empresas')),
                ('filiais_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Filiais')),
                ('storage_mb', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Armazenamento (MB)')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Usuário que excluiu o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('owner', models.ForeignKey(blank=True, help_text='Proprietário do registro (pode ser diferente de quem criou)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota_usage', to='tenants.tenant', verbose_name='Tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que fez a última modificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Uso de Quota',
                'verbose_name_plural': 'Usos de Quota',
                'indexes': [models.Index(fields=['tenant'], name='subscriptio_tenant__ad0e6a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['is_active', 'display_order'], name='subscriptio_is_acti_fd1009_idx'),
        ),
    ]
