# Generated by Django 4.2.27 on 2025-12-20 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
    ]
