# Generated by Django 4.2.27 on 2025-12-21 19:07
# Migration segura que verifica se os campos já existem antes de adicionar

from django.db import migrations, models, connection


def add_fields_if_not_exist(apps, schema_editor):
    """Adiciona campos apenas se eles não existirem"""
    with connection.cursor() as cursor:
        # Verificar se stripe_price_id_monthly já existe
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='subscriptions_plan' AND column_name='stripe_price_id_monthly'
        """)
        monthly_exists = cursor.fetchone() is not None
        
        # Verificar se stripe_price_id_yearly já existe
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='subscriptions_plan' AND column_name='stripe_price_id_yearly'
        """)
        yearly_exists = cursor.fetchone() is not None
        
        # Adicionar stripe_price_id_monthly se não existir
        if not monthly_exists:
            cursor.execute("""
                ALTER TABLE subscriptions_plan 
                ADD COLUMN stripe_price_id_monthly VARCHAR(255) NULL
            """)
        
        # Adicionar stripe_price_id_yearly se não existir
        if not yearly_exists:
            cursor.execute("""
                ALTER TABLE subscriptions_plan 
                ADD COLUMN stripe_price_id_yearly VARCHAR(255) NULL
            """)


def reverse_add_fields(apps, schema_editor):
    """Não faz nada no rollback para evitar perda de dados"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_add_pending_status'),
    ]

    operations = [
        migrations.RunPython(
            add_fields_if_not_exist,
            reverse_add_fields,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Já foi feito no RunPython
            state_operations=[
                migrations.AddField(
                    model_name='plan',
                    name='stripe_price_id_monthly',
                    field=models.CharField(blank=True, help_text='ID do preço mensal no Stripe (ex: price_xxx)', max_length=255, null=True, verbose_name='Stripe Price ID (Mensal)'),
                ),
                migrations.AddField(
                    model_name='plan',
                    name='stripe_price_id_yearly',
                    field=models.CharField(blank=True, help_text='ID do preço anual no Stripe (ex: price_xxx)', max_length=255, null=True, verbose_name='Stripe Price ID (Anual)'),
                ),
                migrations.AlterField(
                    model_name='subscription',
                    name='status',
                    field=models.CharField(choices=[('trial', 'Trial'), ('pending', 'Aguardando Pagamento'), ('active', 'Ativa'), ('past_due', 'Pagamento Atrasado'), ('canceled', 'Cancelada'), ('expired', 'Expirada')], default='trial', max_length=20, verbose_name='Status'),
                ),
            ],
        ),
    ]
