# Generated by Django 4.2.27 on 2026-01-11 18:06

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0003_remove_contareceber_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0004_tenant_last_backup_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro', verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica se o registro foi excluído (soft delete)', verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi excluído', null=True, verbose_name='Data de Exclusão')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Quantidade × Valor Unitário', max_digits=10, verbose_name='Valor Total')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Desconto')),
                ('cfop', models.CharField(blank=True, help_text='Código Fiscal de Operações e Prestações', max_length=4, null=True, verbose_name='CFOP')),
                ('ncm', models.CharField(blank=True, help_text='Nomenclatura Comum do Mercosul', max_length=10, null=True, verbose_name='NCM')),
                ('unidade_medida', models.CharField(default='UN', max_length=10, verbose_name='Unidade de Medida')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Item de Nota Fiscal',
                'verbose_name_plural': 'Itens de Nota Fiscal',
                'ordering': ['nota_fiscal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NotaFiscalServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro', verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica se o registro foi excluído (soft delete)', verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi excluído', null=True, verbose_name='Data de Exclusão')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('codigo_verificacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Verificação')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('AUTORIZADA', 'Autorizada'), ('CANCELADA', 'Cancelada'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_emissao', models.DateTimeField(verbose_name='Data de Emissão')),
                ('data_autorizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Autorização')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Total')),
                ('pdf_path', models.FileField(blank=True, null=True, upload_to='nfse_pdfs/', verbose_name='PDF da NFSe')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais_servico_recebidas', to='cadastros.pessoa', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Usuário que excluiu o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais_servico', to='tenants.empresa', verbose_name='Empresa')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais_servico', to='tenants.filial', verbose_name='Filial')),
                ('owner', models.ForeignKey(blank=True, help_text='Proprietário do registro (pode ser diferente de quem criou)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais_servico', to='cadastros.servico', verbose_name='Serviço')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que fez a última modificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Nota Fiscal de Serviços',
                'verbose_name_plural': 'Notas Fiscais de Serviços',
                'ordering': ['-data_emissao', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='NotaFiscalEletronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro', verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica se o registro foi excluído (soft delete)', verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Data e hora em que o registro foi excluído', null=True, verbose_name='Data de Exclusão')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('serie', models.CharField(default='1', max_length=3, verbose_name='Série')),
                ('chave_acesso', models.CharField(blank=True, help_text='Chave de acesso da NF-e (44 caracteres)', max_length=44, null=True, unique=True, verbose_name='Chave de Acesso')),
                ('status_sefaz', models.CharField(choices=[('PENDENTE', 'Pendente'), ('AUTORIZADA', 'Autorizada'), ('CANCELADA', 'Cancelada'), ('INUTILIZADA', 'Inutilizada'), ('REJEITADA', 'Rejeitada'), ('DENEGADA', 'Denegada')], default='PENDENTE', max_length=20, verbose_name='Status SEFAZ')),
                ('protocolo_autorizacao', models.CharField(blank=True, help_text='Protocolo retornado pela SEFAZ', max_length=50, null=True, verbose_name='Protocolo de Autorização')),
                ('xml_assinado', models.TextField(blank=True, help_text='XML completo da NF-e assinado', null=True, verbose_name='XML Assinado')),
                ('xml_retorno', models.TextField(blank=True, help_text='XML de retorno da SEFAZ', null=True, verbose_name='XML de Retorno')),
                ('pdf_path', models.FileField(blank=True, null=True, upload_to='nfe_pdfs/', verbose_name='PDF da NF-e')),
                ('data_emissao', models.DateTimeField(verbose_name='Data de Emissão')),
                ('data_autorizacao', models.DateTimeField(blank=True, help_text='Data em que a NF-e foi autorizada pela SEFAZ', null=True, verbose_name='Data de Autorização')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Cancelamento')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Total')),
                ('valor_produtos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor dos Produtos')),
                ('valor_impostos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor dos Impostos')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Frete')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Desconto')),
                ('justificativa_cancelamento', models.TextField(blank=True, help_text='Justificativa para cancelamento da NF-e', null=True, verbose_name='Justificativa de Cancelamento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais_recebidas', to='cadastros.pessoa', verbose_name='Cliente/Destinatário')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Usuário que excluiu o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='tenants.empresa', verbose_name='Empresa')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='tenants.filial', verbose_name='Filial')),
                ('owner', models.ForeignKey(blank=True, help_text='Proprietário do registro (pode ser diferente de quem criou)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Nota Fiscal Eletrônica',
                'verbose_name_plural': 'Notas Fiscais Eletrônicas',
                'ordering': ['-data_emissao', '-numero'],
            },
        ),
    ]
