# Generated by Django 4.2.27 on 2026-01-11 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendas', '0001_initial'),
        ('cadastros', '0003_remove_contareceber_cliente_and_more'),
        ('faturamento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscaleletronica',
            name='pedido_venda',
            field=models.ForeignKey(blank=True, help_text='Pedido de venda que originou esta NF-e', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='vendas.pedidovenda', verbose_name='Pedido de Venda'),
        ),
        migrations.AddField(
            model_name='notafiscaleletronica',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que fez a última modificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
        migrations.AddField(
            model_name='itemnotafiscal',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='itemnotafiscal',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que excluiu o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='itemnotafiscal',
            name='nota_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='faturamento.notafiscaleletronica', verbose_name='Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='itemnotafiscal',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Proprietário do registro (pode ser diferente de quem criou)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário'),
        ),
        migrations.AddField(
            model_name='itemnotafiscal',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_nota_fiscal', to='cadastros.produto', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='itemnotafiscal',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que fez a última modificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
        migrations.AddIndex(
            model_name='notafiscalservico',
            index=models.Index(fields=['empresa', 'status'], name='faturamento_empresa_10e8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscalservico',
            index=models.Index(fields=['cliente', 'data_emissao'], name='faturamento_cliente_1b8c65_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscaleletronica',
            index=models.Index(fields=['empresa', 'status_sefaz'], name='faturamento_empresa_46d151_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscaleletronica',
            index=models.Index(fields=['cliente', 'data_emissao'], name='faturamento_cliente_11aa91_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscaleletronica',
            index=models.Index(fields=['chave_acesso'], name='faturamento_chave_a_9e736f_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscaleletronica',
            index=models.Index(fields=['numero', 'serie'], name='faturamento_numero_9ac263_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscaleletronica',
            index=models.Index(fields=['pedido_venda'], name='faturamento_pedido__72c46f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notafiscaleletronica',
            unique_together={('numero', 'serie', 'empresa')},
        ),
        migrations.AddIndex(
            model_name='itemnotafiscal',
            index=models.Index(fields=['nota_fiscal', 'produto'], name='faturamento_nota_fi_643a41_idx'),
        ),
    ]
